---
- name: Install Docker
  hosts: localhost

  tasks:
  - name: Install ca-certificates
    become: yes
    apt:
      name: ca-certificates
      state: present
      update-cache: no

  - name: Download Docker gpg key
    become: yes
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Add repository to apt sources
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian trixie stable"
      create: yes

  - name: Install Docker
    become: yes
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      update_cache: yes

  - name: Create the docker group
    become: yes
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add the user to the docker group
    become: yes
    ansible.builtin.user:
      name: jacobl
      groups: docker
      append: yes
