---
- name: Install .NET
  hosts: localhost

  tasks:
  - name: Download MS product repository
    get_url:
    # still using Debian 12 (Bookworm) packages because Debian 13
    # (Trixie) packages not available yet.
      url: https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb

  - name: Install MS product repository
    become: yes
    apt: deb=/tmp/packages-microsoft-prod.deb
    
  - name: Make sure HTTPS is supported by apt
    become: yes
    apt:
      name: apt-transport-https
      state: present
      update_cache: no
    
  - name: Install .NET 8 SDK
    become: yes
    apt:
      name: dotnet-sdk-8.0
      state: present
      update_cache: yes

  - name: Install .NET 9 SDK
    become: yes
    apt:
      name: dotnet-sdk-9.0
      state: present
      update_cache: yes

  - name: Update workloads
    become: yes
    shell: dotnet workload update

  # TODO: figure out how to ignore errors, then can uncomment this task
  # - name: Trust certificate
    # ignore-errors: true
    # shell: dotnet dev-certs https --trust

  - name: Install csharp-ls
    shell: dotnet tool install --global csharp-ls

